---
  language: go
  dist: xenial 
  notifications:
    email: false
  os:
    - linux
  before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -qq -y docker-engine linux-headers-generic flex bison libgpgme11-dev libdevmapper-dev btrfs-\*
  sudo: required
  services:
    - docker
  install: "make all"
  script: "make test-ci"
  go:
    - "1.7.4"
